project_id = "qgtqiqileuoszacdmjnk"

[functions.assign-routine]
verify_jwt = true

[functions.get-user-routine]
verify_jwt = true

[functions.record-progress]
verify_jwt = true

[functions.get-progress]
verify_jwt = true

[functions.get-progress-stats]
verify_jwt = true

[functions.get-routines]
verify_jwt = false

[functions.get-todays-workouts]
verify_jwt = true

[functions.get-workouts-by-date]
verify_jwt = true
