version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout
      
      # Restaurar caché de dependencias
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      
      # Instalar dependencias
      - run:
          name: Install Dependencies
          command: npm ci
      
      # Guardar caché de dependencias
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      
      # Ejecutar linter
      - run:
          name: Run Linter
          command: npm run lint || true
      
      # Build del proyecto
      - run:
          name: Build Project
          command: npm run build
      
      # Guardar artefactos del build
      - store_artifacts:
          path: dist
          destination: build-output
      
      # Persistir el workspace para otros jobs
      - persist_to_workspace:
          root: .
          paths:
            - dist

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - main
                - develop
